//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microflake.Core.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microflake.Core.Lang.Validations", typeof(Validations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string _2characterslong {
            get {
                return ResourceManager.GetString("2characterslong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name is Required.
        /// </summary>
        public static string categoryNameRequired {
            get {
                return ResourceManager.GetString("categoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecommerce.
        /// </summary>
        public static string Ecommerce {
            get {
                return ResourceManager.GetString("Ecommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already in use..
        /// </summary>
        public static string Name_already_in_use_ {
            get {
                return ResourceManager.GetString("Name already in use.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Alphabits are Allowed .
        /// </summary>
        public static string OnlyAlphabats {
            get {
                return ResourceManager.GetString("OnlyAlphabats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredPrice.
        /// </summary>
        public static string RequiredPrice {
            get {
                return ResourceManager.GetString("RequiredPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is Required.
        /// </summary>
        public static string RequiredQty {
            get {
                return ResourceManager.GetString("RequiredQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price is Required.
        /// </summary>
        public static string RequiredsellingPrice {
            get {
                return ResourceManager.GetString("RequiredsellingPrice", resourceCulture);
            }
        }
    }
}
