// <auto-generated />
namespace Microflake.Core.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class grandtotal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(grandtotal));
        
        string IMigrationMetadata.Id
        {
            get { return "202207031145203_grandtotal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
